apiVersion: v1
kind: Service
metadata:
  name: {{ include "eduhelx-file-api.fullname" . }}
  labels:
    {{- include "eduhelx-file-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "eduhelx-file-api.selectorLabels" . | nindent 4 }}
